### ISSUE TITLE
[Fix] Desktop build CI job missing SDK main override — fails on new SDK exports [CI]

### ISSUE THREAD

**Issue by Ehsan-saradar** [vultisig/vultisig-windows#3684]
# [Fix] Desktop build CI job missing SDK main override — fails on new SDK exports [CI]

## Problem

The `lint` and `extension` CI jobs clone the SDK main branch, build it, and override `@vultisig/*` packages via tarball resolutions. The `build` job (Wails desktop, runs on both `ubuntu-22.04` and `windows-latest`) does **not** have this override. It uses the published npm versions instead.

This means any PR that imports from a new SDK export (merged to SDK main but not yet published to npm) will pass `lint` and `extension` but fail `build`. This was hit in #3638 where `@vultisig/core-chain/chains/polkadot/dapp/...` exports existed on SDK main but not in the published `@vultisig/core-chain@1.0.0`.

## Expected Behavior

The `build` job should use SDK main, consistent with `lint` and `extension`.

## Steps to Reproduce

1. Add a new export to `vultisig-sdk` and merge to main (don't publish to npm)
2. Import from that new export in `vultisig-windows`
3. `lint` and `extension` pass, `build` fails with `Cannot find module`

## Solution

Add the same "Clone and build SDK main" + "Override SDK packages with main branch" steps to the `build` job. The challenge is that `build` runs on `windows-latest` where:
- `/tmp/` paths don't work (use `$RUNNER_TEMP`)
- Yarn's hardened mode on public PRs causes `yarn install` to exit non-zero on warnings
- `shell: bash` is needed for heredoc/for-loop syntax
- `corepack prepare` may conflict with the SDK's own Yarn version

Previous attempts failed on Windows due to `yarn install` exiting non-zero in hardened mode. The `|| true` workaround didn't help. May need to investigate `YARN_ENABLE_HARDENED_MODE=0` as a runner-level env, or split the SDK build into a separate reusable action.

### Must Do
- [ ] Add SDK main override to the `build` job in `build.yml`
- [ ] Ensure it works on both `ubuntu-22.04` and `windows-latest`
- [ ] Test with a PR that imports from a new (unpublished) SDK export

### Must NOT Do
- Don't change `lint` or `extension` jobs (they already work)
- Don't change unrelated CI config

### Out of Scope
- Extracting SDK override into a reusable composite action (nice-to-have follow-up)

## Acceptance Criteria
- [ ] `build` job passes on both Linux and Windows
- [ ] PRs importing new SDK exports pass all CI jobs
- [ ] Existing PRs not touching SDK imports are unaffected

## Context
- Related PR: #3638 (workaround: kept local copies of SDK files)
- Related issue: #3676 (SDK migration blocked by this)
- SDK PR with new exports: vultisig/vultisig-sdk#177
